# Generated by Django 4.2 on 2023-09-01 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_place_place_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['order_number']},
        ),
    ]
