# Generated by Django 4.2 on 2023-09-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_alter_place_description_long_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='description_long',
            new_name='long_description',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='description_short',
            new_name='short_description',
        ),
        migrations.RemoveField(
            model_name='place',
            name='place_id',
        ),
        migrations.AlterField(
            model_name='image',
            name='order_number',
            field=models.PositiveIntegerField(blank=True, db_index=True, default=0, verbose_name='Порядковый номер'),
        ),
    ]
